name: Feature Request
description: Suggest a new feature or enhancement for PyTWAT
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide details below to help us understand your idea.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Describe the issue you're facing.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature or enhancement you'd like to see.
      placeholder: |
        I'd like PyTWAT to support...

        This would work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've considered... but it doesn't work because...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important
        - Critical
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area of PyTWAT does this feature relate to?
      options:
        - GUI / User Interface
        - Terminal / Display
        - Trade Wars Parser
        - Automation / Scripts
        - Database / Storage
        - Network / Connectivity
        - Documentation
        - Testing
        - Other
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how you would use this feature. Provide examples if possible.
      placeholder: |
        As a Trade Wars player, I want to...

        Example scenario:
        1. ...
        2. ...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, screenshots, or examples about the feature.
      placeholder: Here's a mockup of how this could look...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting.
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have read the project roadmap (PYTWAT-PLAN.md) to check if this is already planned
          required: false
        - label: This feature aligns with PyTWAT's goals as a Trade Wars 2002 client
          required: true
